title: My GitHub Pages Site
description: This is my website.
theme: minima

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Author settings
author:
  name: Your Name
  email: your-email@example.com

# Social media settings
social:
  twitter: yourusername
  github: yourusername

# Build settings
markdown: kramdown


