title: MJ's Project Portfolio
description: This is my website.
theme: jekyll-theme-minimal


author:
  name: Monjolajesu Ayotunde Adeyeye
  email: Monjolajesuaadeyeye@gmail.com

# Markdown settings
markdown: kramdown
