title: MJ's Project Portfolio
description: This is my website.
theme: Minima


author:
  name: Monjolajesu Ayotunde Adeyeye
  email: Monjolajesuaadeyeye@gmail.com

# Markdown settings
markdown: kramdown
